/*-------------------------------------------------------------------------
 *
 * svgkwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2022, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef SVGKWLIST_D_H
#define SVGKWLIST_D_H

#include "common/kwlookup.h"

static const char ScanKeywords_kw_string[] =
	"aliceblue\0"
	"antiquewhite\0"
	"aqua\0"
	"aquamarine\0"
	"azure\0"
	"beige\0"
	"bisque\0"
	"black\0"
	"blanchedalmond\0"
	"blue\0"
	"blueviolet\0"
	"brown\0"
	"burlywood\0"
	"cadetblue\0"
	"chartreuse\0"
	"chocolate\0"
	"circle\0"
	"coral\0"
	"cornflowerblue\0"
	"cornsilk\0"
	"crimson\0"
	"cx\0"
	"cy\0"
	"cyan\0"
	"darkblue\0"
	"darkcyan\0"
	"darkgoldenrod\0"
	"darkgray\0"
	"darkgreen\0"
	"darkgrey\0"
	"darkkhaki\0"
	"darkmagenta\0"
	"darkolivegreen\0"
	"darkorange\0"
	"darkorchid\0"
	"darkred\0"
	"darksalmon\0"
	"darkseagreen\0"
	"darkslateblue\0"
	"darkslategray\0"
	"darkslategrey\0"
	"darkturquoise\0"
	"darkviolet\0"
	"deeppink\0"
	"deepskyblue\0"
	"def\0"
	"dimgray\0"
	"dimgrey\0"
	"dodgerblue\0"
	"fill\0"
	"firebrick\0"
	"floralwhite\0"
	"forestgreen\0"
	"fuchsia\0"
	"gainsboro\0"
	"ghostwhite\0"
	"gold\0"
	"goldenrod\0"
	"gray\0"
	"green\0"
	"greenyellow\0"
	"grey\0"
	"group\0"
	"height\0"
	"honeydew\0"
	"hotpink\0"
	"id\0"
	"image\0"
	"indianred\0"
	"indigo\0"
	"ivory\0"
	"khaki\0"
	"lavender\0"
	"lavenderblush\0"
	"lawngreen\0"
	"lemonchiffon\0"
	"lightblue\0"
	"lightcoral\0"
	"lightcyan\0"
	"lightgoldenrodyellow\0"
	"lightgray\0"
	"lightgreen\0"
	"lightgrey\0"
	"lightpink\0"
	"lightsalmon\0"
	"lightseagreen\0"
	"lightskyblue\0"
	"lightslategray\0"
	"lightslategrey\0"
	"lightsteelblue\0"
	"lightyellow\0"
	"lime\0"
	"limegreen\0"
	"line\0"
	"linen\0"
	"magenta\0"
	"marker\0"
	"maroon\0"
	"mediumaquamarine\0"
	"mediumblue\0"
	"mediumorchid\0"
	"mediumpurple\0"
	"mediumseagreen\0"
	"mediumslateblue\0"
	"mediumspringgreen\0"
	"mediumturquoise\0"
	"mediumvioletred\0"
	"midnightblue\0"
	"mintcream\0"
	"mistyrose\0"
	"moccasin\0"
	"navajowhite\0"
	"navy\0"
	"oldlace\0"
	"olive\0"
	"olivedrab\0"
	"orange\0"
	"orangered\0"
	"orchid\0"
	"palegoldenrod\0"
	"palegreen\0"
	"paleturquoise\0"
	"palevioletred\0"
	"papayawhip\0"
	"path\0"
	"peachpuff\0"
	"peru\0"
	"pink\0"
	"plum\0"
	"powderblue\0"
	"purple\0"
	"rect\0"
	"red\0"
	"rgb\0"
	"rosybrown\0"
	"royalblue\0"
	"saddlebrown\0"
	"salmon\0"
	"sandybrown\0"
	"seagreen\0"
	"seashell\0"
	"sienna\0"
	"silver\0"
	"skyblue\0"
	"slateblue\0"
	"slategray\0"
	"slategrey\0"
	"snow\0"
	"springgreen\0"
	"steelblue\0"
	"stroke\0"
	"style\0"
	"svg\0"
	"tan\0"
	"teal\0"
	"thistle\0"
	"tomato\0"
	"transform\0"
	"translate\0"
	"turquoise\0"
	"violet\0"
	"wheat\0"
	"white\0"
	"whitesmoke\0"
	"width\0"
	"xmlns\0"
	"yellow\0"
	"yellowgreen";

static const uint16 ScanKeywords_kw_offsets[] = {
	0,
	10,
	23,
	28,
	39,
	45,
	51,
	58,
	64,
	79,
	84,
	95,
	101,
	111,
	121,
	132,
	142,
	149,
	155,
	170,
	179,
	187,
	190,
	193,
	198,
	207,
	216,
	230,
	239,
	249,
	258,
	268,
	280,
	295,
	306,
	317,
	325,
	336,
	349,
	363,
	377,
	391,
	405,
	416,
	425,
	437,
	441,
	449,
	457,
	468,
	473,
	483,
	495,
	507,
	515,
	525,
	536,
	541,
	551,
	556,
	562,
	574,
	579,
	585,
	592,
	601,
	609,
	612,
	618,
	628,
	635,
	641,
	647,
	656,
	670,
	680,
	693,
	703,
	714,
	724,
	745,
	755,
	766,
	776,
	786,
	798,
	812,
	825,
	840,
	855,
	870,
	882,
	887,
	897,
	902,
	908,
	916,
	923,
	930,
	947,
	958,
	971,
	984,
	999,
	1015,
	1033,
	1049,
	1065,
	1078,
	1088,
	1098,
	1107,
	1119,
	1124,
	1132,
	1138,
	1148,
	1155,
	1165,
	1172,
	1186,
	1196,
	1210,
	1224,
	1235,
	1240,
	1250,
	1255,
	1260,
	1265,
	1276,
	1283,
	1288,
	1292,
	1296,
	1306,
	1316,
	1328,
	1335,
	1346,
	1355,
	1364,
	1371,
	1378,
	1386,
	1396,
	1406,
	1416,
	1421,
	1433,
	1443,
	1450,
	1456,
	1460,
	1464,
	1469,
	1477,
	1484,
	1494,
	1504,
	1514,
	1521,
	1527,
	1533,
	1544,
	1550,
	1556,
	1563,
};

#define SCANKEYWORDS_NUM_KEYWORDS 168

static int
ScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[337] = {
		31,    1,     -45,   -18,   32767, 32767, 32767, 32767,
		-76,   32767, 32767, 309,   39,    32767, 0,     101,
		32767, 49,    32767, 169,   -235,  4,     32767, -76,
		157,   -34,   37,    32767, 32767, 42,    32767, 145,
		19,    -30,   175,   -105,  0,     0,     32767, 32767,
		32767, 12,    0,     32767, -12,   66,    60,    79,
		32767, 32767, 226,   32767, 32767, 32767, 67,    81,
		93,    137,   50,    32767, -206,  0,     -114,  32767,
		82,    32767, 78,    3,     32767, 0,     -100,  -124,
		183,   40,    228,   0,     45,    176,   32767, 307,
		32767, 6,     0,     32767, 32767, 42,    11,    17,
		32767, 0,     -61,   152,   0,     214,   32767, 51,
		32767, -13,   32767, 32767, 32767, 32767, 47,    -11,
		32767, 32767, 80,    107,   -31,   119,   42,    32767,
		32767, 150,   32767, 0,     32767, 32767, 33,    263,
		-100,  103,   109,   166,   32767, 132,   -305,  0,
		48,    95,    32767, -75,   27,    0,     32767, 32767,
		41,    63,    373,   32767, 72,    0,     32767, -51,
		28,    36,    76,    -98,   32767, 29,    0,     -284,
		-66,   32767, 0,     32767, 0,     32767, 32767, 32767,
		32767, 81,    -10,   69,    95,    32767, 208,   32767,
		-64,   83,    32767, 32767, 32767, 114,   32767, 32767,
		32767, 32767, 32767, 115,   32767, 32767, 0,     32767,
		94,    88,    32767, -182,  32767, -48,   164,   73,
		105,   -11,   -148,  0,     54,    32767, 237,   32767,
		91,    32767, 155,   106,   32767, 32767, 32767, 32767,
		0,     32767, 32767, 32767, 32767, 86,    -1,    32767,
		32767, 36,    48,    32767, 0,     115,   0,     32767,
		93,    183,   124,   32767, 75,    0,     32767, -63,
		225,   32767, 34,    32767, 0,     73,    0,     135,
		0,     0,     32767, 61,    32767, 23,    32767, 143,
		368,   54,    27,    42,    32767, -15,   143,   0,
		0,     32767, 32767, 15,    0,     32767, 32767, 32767,
		32767, 199,   0,     251,   32767, 100,   32767, -1,
		-92,   32767, 0,     -255,  181,   -178,  76,    57,
		0,     119,   20,    0,     14,    -221,  -18,   32767,
		121,   146,   32767, 38,    32767, -119,  32767, 32767,
		121,   68,    32767, 32767, 32767, -113,  65,    0,
		32767, 32767, 0,     130,   0,     139,   32767, 54,
		32767, 32767, -17,   32767, 13,    32767, 32767, 32767,
		0,     32767, 32767, 32767, 0,     32767, 68,    141,
		0,     32767, 32767, 290,   0,     0,     72,    0,
		136
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 1;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 17 + c;
	}
	return h[a % 337] + h[b % 337];
}

static const ScanKeywordList ScanKeywords = {
	ScanKeywords_kw_string,
	ScanKeywords_kw_offsets,
	ScanKeywords_hash_func,
	SCANKEYWORDS_NUM_KEYWORDS,
	20
};

#endif							/* SVGKWLIST_D_H */
